### PR TITLE
Fix deprecated syntax @doc

### LINKED ISSUE #14: Deprecated syntax `@doc call with ->`
Hello @dysonance ,

Running tests displays

```
┌ Warning: Deprecated syntax `@doc call with ->` at /Users/femto/.julia/packages/Indicators/rjUJD/src/run.jl:19.
│ Use `a line break` instead.
└ @ ~/.julia/packages/Indicators/rjUJD/src/run.jl:19
```

Best regards

### PR DESCRIPTION
**Pull request by femtotrader**
Fix deprecated syntax `@doc`
Format docstring as mentioned in https://github.com/JuliaDocs/Documenter.jl/blob/master/docs/src/man/guide.md#adding-some-docstrings

Closes #14

### CODE REVIEW

**Comment by JTAmos** [comment]
Thanks again for the help, looks good. Also appreciate the reference to the new documentation convention, wasn't aware of this style until now.

**Comment by femtotrader** [comment]
My pleasure @dysonance ... could you have a look at your LinkedIn also for private discussion?

**Comment by JTAmos** [comment]
@femtotrader Sure, just checked my LinkedIn, no new invites or messages. Should I be expecting something?

**Comment by femtotrader** [comment]
Invite sent (again!!)... but you can also email me at https://femtotrader.github.io/ (see below)

**Comment by femtotrader** [comment]
Invite sent (again!!) but it looks like as if you was refusing it.

**Pull request merged**
